- name: Create a nginx server with site
  hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - group_vars/env
  vars:
      ansible_python_interpreter: /usr/bin/python3

  tasks:
  - name: create VPC
    amazon.aws.ec2_vpc_net:
      name: "{{ vpc_name }}"
      cidr_block: "{{ network }}"
      region: "{{ aws_region }}"
      state: present
      dns_hostnames: yes
      dns_support: yes
      multi_ok: no
      tags:
        Name: "{{ vpc_name }}"
    register: vpc

  - name: Add VPC definition to vars file
    lineinfile:
      path: group_vars/colman.env
      regexp: 'vpc_id: '
      line: 'vpc_id: {{ vpc.vpc.id }}'
      state: present
      create: True

  - name: associate subnet to the VPC
    amazon.aws.ec2_vpc_subnet:
      state: present
      vpc_id: "{{ vpc.vpc.id }}"
      region: "{{ aws_region }}"
      cidr: "{{ subnet_cidr }}"
      map_public: yes
      az: "{{ subnet }}"
      resource_tags:
        Name: "{{ vpc_name }}"
      wait: yes
    register: subnet

  - name: Add subnet definition to vars file
    ansible.builtin.lineinfile:
      path: group_vars/colman.env
      regexp: 'subnet_id: '
      line: 'subnet_id: {{ subnet.subnet.id }}'
      state: present
      create: True

  - name: create IGW
    amazon.aws.ec2_vpc_igw:
     vpc_id: "{{ vpc.vpc.id }}"
     region: "{{ aws_region }}"
     state: present
     tags:
       Name: "{{ vpc_name }}_igw"
    register: igw

  #- debug: var=igw

  - name: Add IGW definition to vars file
    ansible.builtin.lineinfile:
      path: group_vars/colman.env
      regexp: 'igw_id: '
      line: 'igw_id: {{ igw.gateway_id}}'
      state: present
      create: True

  - name: Route table for public Subnet
    amazon.aws.ec2_vpc_route_table:
      vpc_id: "{{ vpc.vpc.id }}"
      region: "{{ aws_region }}"
      state: present
      subnets:
        - "{{ subnet.subnet.id }}"
      routes:
        - dest: 0.0.0.0/0
          gateway_id: "{{ igw.gateway_id  }}"
      tags:
        Name: "{{ vpc_name }}_public_rt"

  - name: Create security group
    ec2_group:
      name: "{{ vpc_name }} VPC SG"
      description: "{{ vpc_name }} VPC SG"
      vpc_id: "{{ vpc.vpc.id }}"
      region: "{{ aws_region }}"
      state: present
      rules:
        - proto: tcp
          ports:
          - 80
          - 22
          cidr_ip: 0.0.0.0/0
    register: sg

  - name: Create server
    amazon.aws.ec2_instance:
      image_id: "{{ aws_ubuntu_ami }}"
      wait: yes
      instance_type: "{{ Server_type }}"
      region: "{{ aws_region }}"
      security_group: "{{ sg.group_id }}"
      vpc_subnet_id: "{{ subnet.subnet.id }}"
      key_name: "{{ keypair }}"
      volumes:
        - device_name: /dev/sda1
          ebs:
            volume_type: gp3
            volume_size: "{{ server_volume_size }}"
            delete_on_termination: true
      tags:
        Name: "{{ server_name }}"
        Environment: "{{ env }}"
      exact_count: 1
      wait_timeout: 300
      network:
        assign_public_ip: yes
      state: running
    register: server_ec2

  - name: get ip of instance
    amazon.aws.ec2_instance_info:
      filters:
        "tag:Name": "{{ server_name }}"
        instance-state-name: [ "running"]
    register: ec2_data

  - debug: var=ec2_data

  - debug: var=ec2_data.instances[0].public_ip_address

  - name: Add server public IP to application host group
    add_host: hostname={{ ec2_data.instances[0].public_ip_address }} groups=app

  - name: Add Public IP definition to vars file
    ansible.builtin.lineinfile:
      path: group_vars/colman.env
      regexp: 'server_id: '
      line: 'server_id: {{ ec2_data.instances[0].instance_id }}'
      state: present
      create: True

  - name: Wait for SSH to start using external IP
    wait_for:
      host: "{{ ec2_data.instances[0].public_ip_address }}"
      port: 22
      timeout: 300

# ##############################################################
- name: Setup web server
  hosts: app
  user: ubuntu
  become: True
  gather_facts: True
  vars_files:
    - group_vars/env
  tasks:

    - name: install base packages
      ansible.builtin.apt: 
        name: 
          - git
          - nginx
        update_cache: yes
        state: present

    - name: restart nginx
      service:
        name: nginx
        state: restarted
        enabled: yes
