name: deploy my app to cloud

on:
  push:
    branches: [ deployment ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python 3.10
        uses: actions/setup-python@v6
        with:
            python-version: '3.10'
      - name: Install dependencies
        run: |
            sudo apt-add-repository ppa:ansible/ansible
            python -m pip install --upgrade pip
            pip install ansible==10.7.0 requests google-auth==2.48.0
      - name: 'Authenticate to Google Cloud'
        id: 'auth'
        uses: 'google-github-actions/auth@v3'
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCUNT }}'
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      - name: run playbook
        run: |
          ansible-playbook deploy_calc.yml
